module.exports = {
  TESTS: "/tests",
  TEST_ID: "/test/:id",
  EDIT_TEST_ID: "/test/edit/:id",
  LOGIN: "/login",
  LOGOUT: "/logout",
  PRODUCTS: "/products",
  PRODUCT_ID: "/product/:id",
  EDIT_PRODUCT_ID: "/product/edit/:id",
  USERS: "/users",
  USER_ID: "/user/:id",
  EDIT_USER_ID: "/user/edit/:id",
  SERVICE: "/service",
  SERVICE_ID: "/service/:id",
  EDIT_SERVICE_ID: "/service/edit/:id",
  SCHEDULES: "/schedules",
  SCHEDULE_ID: "/schedule/:id",
  EDIT_SCHEDULE_ID: "/schedule/edit/:id",
};
