module.exports = {
  TESTS: "/tests",
  TEST_ID: "/test/:id",
  LOGIN: "/login",
  LOGOUT: "/logout",
  EDIT_TEST_ID: "/test/edit/:id",
  PRODUCTS: "/products",
  PRODUCT_ID: "/products/:id",
  PRODUCT_STORE: "/products/store",
  EDIT_PRODUCT_ID: "/products/edit/:id",
  DELETE_PRODUCT_ID: "/products/delete/:id",
  USERS: "/users",
  USER_ID: "/user/:id",
  EDIT_USER_ID: "/user/edit/:id",
};
