module.exports = {
  TEST: "test",
  USER: "user",
  SCHEDULE: "schedule",
  IMAGES: "images",
  IMAGE: "image",
  PRODUCT: "product",
  PRODUCTION: "production",
  NONE: "none",
  JWT: "jwt",
  SERVICE: "service",
  DELIVERY: "delivery",
  COMMENT: "comment",
  TRANSACTION: "transaction",
  APPOINTMENT: "appointment",
  REQUIREMENT: "requirement",
  INFORMATION: "information",
  VERIFICATION: "verification",
  FEEDBACK: "feedback",
  BRAND: "brand",
  TIME: "time",
  MONTH: "month",
  OPTION: "option",
  EXCLUSION: "exclusions",
};
